FROM ubuntu:15.04
MAINTAINER datawarehouse <aus-eng-data-warehouse@rmn.com>

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip libpq-dev vim curl

ADD . /nudge/

WORKDIR /nudge/

RUN pip3 install -r requirements.txt
RUN python3 setup.py install

CMD ["python3", "src/nudge/worker/subscription.py"]
