FROM ubuntu:15.04
MAINTAINER datawarehouse <aus-eng-data-warehouse@rmn.com>

RUN apt-get update
RUN apt-get install -y python-dev python-pip libpq-dev vim curl mlocate

RUN apt-get install -y wget

RUN mkdir -p /home/root
RUN cd /home/root
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN /usr/local/bin/pip install awscli

RUN apt-get install -y libmagic-dev \
    libxml2-dev \
    libxmlsec1-dev \
    swig \
    libxslt1-dev

ADD /requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

ADD src/ /src/

RUN updatedb # index all file for a quick search with 'locate'

WORKDIR /src/nudge/service/temp_api

ENV PYTHONPATH=/src/python:${PYTHONPATH}

EXPOSE 9191

CMD ["python", "temp_api.py"]
